/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    Listbox: typeof import('primevue/listbox')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Rule: typeof import('./src/components/Rule.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
